### ISSUE TITLE
Add vimrc NeoBundle support

### ISSUE THREAD

**Issue by stefanbuck** [github-linker/core#13]
Requested from @davidosomething https://github.com/github-linker/chrome-extension/issues/31

**Comment by davidosomething** [comment]
thanks @stefanbuck 

match patterns are, on any .vimrc .gvimrc *.vim

(((Neo)?Bundle(Lazy)?)|Plugin)\s*'(.*)'

**Comment by kwakayama** [comment]
:+1:

**Comment by stefanbuck** [comment]
Moved to https://github.com/github-linker/chrome-extension/issues/31, because this repository will be replaced by the [chrome-extension](https://github.com/github-linker/chrome-extension) repository soon!
