### ISSUE TITLE
Stops working on Chrome40+?

### ISSUE THREAD

**Issue by tunnckoCore** [github-linker/core#15]
I think it stops working when I made last update of chrome. I tried to reinstall it and its the same.

**Comment by tunnckoCore** [comment]
Realize how much I'm addicted to this, that I cant work properly now :D

**Comment by stefanbuck** [comment]
GitHub changed the DOM structure that's the reason. Will try to fix it soon as possible, my addicted friend :wink:

**Comment by tunnckoCore** [comment]
Cool. I can help if needed. Only point where exactly. :D

**Comment by tunnckoCore** [comment]
@stefanbuck awesome! I'll try. :)

**Comment by stefanbuck** [comment]
The publish process may take up to 60 minutes to appear in the Chrome Web Store. Fix version is 3.6.0.4

**Comment by stefanbuck** [comment]
The publish process may take up to 60 minutes to appear in the Chrome Web Store. Fix version is 3.6.0.4

**Comment by tunnckoCore** [comment]
Okey, I did not know that, thanks! :+1:
