### ISSUE TITLE
Add rubygems support

### ISSUE THREAD

**Issue by rayshan** [github-linker/core#16]
E.g.: https://github.com/jekyll/jekyll/blob/master/Gemfile

Thanks!

**Comment by stefanbuck** [comment]
... has been on the roadmap in my head for a while ;) Thanks for putting it here too.

**Comment by thoroc** [comment]
:+1:

**Comment by soberstadt** [comment]
+1 for me

**Comment by stefanbuck** [comment]
Moved to https://github.com/github-linker/chrome-extension/issues/42, because this repository will be replaced by the [chrome-extension](https://github.com/github-linker/chrome-extension) repository soon!
