### ISSUE TITLE
Add npm @scope support

### ISSUE THREAD

**Issue by wayneashleyberry** [github-linker/core#18]
Unless I am mistaken, it doesn't seem like there's any support for scoped packages on npm.

See https://github.com/we-are-next/gh-issues/blob/c5fad5d476668ac7cd99810ed55aab13cb12d176/package.json#L2 as an example.

**Comment by stefanbuck** [comment]
In your example you assume that the `name` property is clickable. This is even not possible for "normal" package files. 

Back to the topic. You're right, npm scope names are not supported, but I don't have any idea how this should work. As far as I know, the scope name isn't linked with the GitHub username and could  point to a npmE account, right? How should I solve this? Can you provide me some examples?

**Comment by wayneashleyberry** [comment]
You're correct @stefanbuck, the scope isn't linked to a GitHub username, it's linked to an npm username.

I haven't looked at any of the source yet, but where npm packages would normally live at npmjs.com/packages/name - scoped packages live at npmjs.com/packages/@scope/name

eg. https://www.npmjs.com/package/@next/gh-issues

**Comment by wayneashleyberry** [comment]
@stefanbuck this seems to have been fixed in the latest release :)
