### ISSUE TITLE
Resolve relative paths

### ISSUE THREAD

**Issue by hedgerworkco** [github-linker/core#20]
I've had the GithubLinker chrome extension installed for a couple of months, and I find that 9 out of 10 times I want to be able to click through to a required module is when it is a module that belongs to the repo that I'm viewing.  (for example, require('../foo/bar')).

i would be willing to implement this, unless you know of some reason that it's not possible.  If you could give me a little insight into how the code flows, you'd spare me the trouble of stepping through it to figure out what's going on, so I'll be way more likely to hurry up and do it!

Thanks!

**Comment by stefanbuck** [comment]
Hi there,

I have good news, this is already implemented. Check out this require statement https://github.com/github-linker/core/blob/master/index.js#L4. Sometimes it takes some time to load (check if the spinner next to "user/repo" appears)

![](https://cloud.githubusercontent.com/assets/1393946/9221520/43dd5fbc-40eb-11e5-97e5-f9eaf82938c3.gif)

**Comment by stefanbuck** [comment]
Closed, because it works fine for me.
