### ISSUE TITLE
Add support for more languages

### ISSUE THREAD

**Issue by ijks** [github-linker/core#21]
Looking through the docs and the source, it seems only JavaScript's `require` is linked. JS is a popular language, but not the only one out there. It would be nice if the extension supported more languages, as the name 'github-linker' implies a scope wider than just `require`.

Examples for a few languages (please comment if I made an error or missed something):

- [ ] [Python][py]
```python
import module
from module import thing
import module as other_module
```
- [ ] [Ruby][rb]
```ruby
require 'file'
require_relative
```
- [ ] [Haskell][hs]
```haskell
import Mod
import qualified Mod
-- A lot of other combinations excluded. See the link.
-- There might also be a formal grammar somewhere.
```
- [ ] [Rust][rs]
```rust
extern crate rust_crate

use rust_crate
use rust_crate::Thing
use rust_crate::Thing as OtherThing
use rust_crate::{ThingOne, ThingTwo}
```
- [ ] [Go][golang]
```go
import "package"
import p "package"
import . "package"
```

And there are of course a lot of other popular languages that support (some form of) modules, like Java, C#, C(++), D, Lisps, OCaml, Perl, etc., but I would suggest limiting support to languages that have a sizable amount of repositories on GitHub. Language-specific package repositories (e.g. CPAN, PyPI, crates.io) could also be used as a fallback when a GitHub repo is not found.

A nice refinement would also be to support linking within a repo when internal modules are imported.

See also: #13, #16, #17, github-linker/chrome-extension#33, github-linker/chrome-extension#37

[py]: https://docs.python.org/3/tutorial/modules.html
[rb]: http://ruby-doc.org/core-2.2.3/Kernel.html#method-i-require
[hs]: https://wiki.haskell.org/Import
[rs]: https://doc.rust-lang.org/reference.html#extern-crate-declarations
[golang]: http://golang.org/ref/spec#Import_declarations

**Comment by stefanbuck** [comment]
Thanks for collection all the stuff together, it is really helpful. I moved all the issues to [chrome-extension](https://github.com/github-linker/chrome-extension/issues), because this will be the new main repository soon. 

After a bigger refactoring of the core, I will start implementing most / all (we will see ) of them step by step.

**Comment by stefanbuck** [comment]
> A nice refinement would also be to support linking within a repo when internal modules are imported.

Btw. this works, but currently just for `require` and `import` statements 

![43dd5fbc-40eb-11e5-97e5-f9eaf82938c3](https://cloud.githubusercontent.com/assets/1393946/9478860/96d36588-4b7a-11e5-9b2c-2fd87d4b6bc9.gif)

**Comment by ijks** [comment]
Great! I might send a PR if I ever get around to learning JS & the Chrome extension API.
